package com.me2me.search.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class SearchHotKeyword implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keyword.id
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keyword.keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keyword.creation_date
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keyword.order_num
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keyword.is_valid
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keyword.is_top
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    private Integer isTop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keyword.id
     *
     * @return the value of hot_keyword.id
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keyword.id
     *
     * @param id the value for hot_keyword.id
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keyword.keyword
     *
     * @return the value of hot_keyword.keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keyword.keyword
     *
     * @param keyword the value for hot_keyword.keyword
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keyword.creation_date
     *
     * @return the value of hot_keyword.creation_date
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keyword.creation_date
     *
     * @param creationDate the value for hot_keyword.creation_date
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keyword.order_num
     *
     * @return the value of hot_keyword.order_num
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keyword.order_num
     *
     * @param orderNum the value for hot_keyword.order_num
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keyword.is_valid
     *
     * @return the value of hot_keyword.is_valid
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keyword.is_valid
     *
     * @param isValid the value for hot_keyword.is_valid
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keyword.is_top
     *
     * @return the value of hot_keyword.is_top
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keyword.is_top
     *
     * @param isTop the value for hot_keyword.is_top
     *
     * @mbggenerated Wed Apr 05 11:41:54 CST 2017
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }
}