package com.me2me.user.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class ImConfig implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_config.id
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_config.uid
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_config.token
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_config.create_time
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_config.id
     *
     * @return the value of im_config.id
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_config.id
     *
     * @param id the value for im_config.id
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_config.uid
     *
     * @return the value of im_config.uid
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_config.uid
     *
     * @param uid the value for im_config.uid
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_config.token
     *
     * @return the value of im_config.token
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_config.token
     *
     * @param token the value for im_config.token
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_config.create_time
     *
     * @return the value of im_config.create_time
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_config.create_time
     *
     * @param createTime the value for im_config.create_time
     *
     * @mbggenerated Sat Apr 01 11:42:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}