package com.me2me.user.model;

import com.me2me.common.web.BaseEntity;

public class JpushToken implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jpush_token.id
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jpush_token.uid
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jpush_token.jpush_token
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    private String jpushToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jpush_token.id
     *
     * @return the value of jpush_token.id
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jpush_token.id
     *
     * @param id the value for jpush_token.id
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jpush_token.uid
     *
     * @return the value of jpush_token.uid
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jpush_token.uid
     *
     * @param uid the value for jpush_token.uid
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jpush_token.jpush_token
     *
     * @return the value of jpush_token.jpush_token
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    public String getJpushToken() {
        return jpushToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jpush_token.jpush_token
     *
     * @param jpushToken the value for jpush_token.jpush_token
     *
     * @mbggenerated Tue Aug 09 15:10:48 CST 2016
     */
    public void setJpushToken(String jpushToken) {
        this.jpushToken = jpushToken == null ? null : jpushToken.trim();
    }
}