package com.me2me.user.model;

import com.me2me.common.web.BaseEntity;

public class PermissionDetails implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.id
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.level
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.big_expression
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer bigExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.typesetting
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer typesetting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.download_img
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer downloadImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.voice_time
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer voiceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.vedio_time
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer vedioTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.massage
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer massage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.kingdom_set
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer kingdomSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.kingdom_steal_num
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer kingdomStealNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_details.steal_limit
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    private Integer stealLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.id
     *
     * @return the value of permission_details.id
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.id
     *
     * @param id the value for permission_details.id
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.level
     *
     * @return the value of permission_details.level
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.level
     *
     * @param level the value for permission_details.level
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.big_expression
     *
     * @return the value of permission_details.big_expression
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getBigExpression() {
        return bigExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.big_expression
     *
     * @param bigExpression the value for permission_details.big_expression
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setBigExpression(Integer bigExpression) {
        this.bigExpression = bigExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.typesetting
     *
     * @return the value of permission_details.typesetting
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getTypesetting() {
        return typesetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.typesetting
     *
     * @param typesetting the value for permission_details.typesetting
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setTypesetting(Integer typesetting) {
        this.typesetting = typesetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.download_img
     *
     * @return the value of permission_details.download_img
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getDownloadImg() {
        return downloadImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.download_img
     *
     * @param downloadImg the value for permission_details.download_img
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setDownloadImg(Integer downloadImg) {
        this.downloadImg = downloadImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.voice_time
     *
     * @return the value of permission_details.voice_time
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getVoiceTime() {
        return voiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.voice_time
     *
     * @param voiceTime the value for permission_details.voice_time
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setVoiceTime(Integer voiceTime) {
        this.voiceTime = voiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.vedio_time
     *
     * @return the value of permission_details.vedio_time
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getVedioTime() {
        return vedioTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.vedio_time
     *
     * @param vedioTime the value for permission_details.vedio_time
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setVedioTime(Integer vedioTime) {
        this.vedioTime = vedioTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.massage
     *
     * @return the value of permission_details.massage
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getMassage() {
        return massage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.massage
     *
     * @param massage the value for permission_details.massage
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setMassage(Integer massage) {
        this.massage = massage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.kingdom_set
     *
     * @return the value of permission_details.kingdom_set
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getKingdomSet() {
        return kingdomSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.kingdom_set
     *
     * @param kingdomSet the value for permission_details.kingdom_set
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setKingdomSet(Integer kingdomSet) {
        this.kingdomSet = kingdomSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.kingdom_steal_num
     *
     * @return the value of permission_details.kingdom_steal_num
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getKingdomStealNum() {
        return kingdomStealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.kingdom_steal_num
     *
     * @param kingdomStealNum the value for permission_details.kingdom_steal_num
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setKingdomStealNum(Integer kingdomStealNum) {
        this.kingdomStealNum = kingdomStealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_details.steal_limit
     *
     * @return the value of permission_details.steal_limit
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public Integer getStealLimit() {
        return stealLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_details.steal_limit
     *
     * @param stealLimit the value for permission_details.steal_limit
     *
     * @mbggenerated Thu Jun 15 15:22:11 CST 2017
     */
    public void setStealLimit(Integer stealLimit) {
        this.stealLimit = stealLimit;
    }
}