package com.me2me.user.model;

import com.me2me.common.web.BaseEntity;

public class UserTips implements BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tips.id
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tips.type
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tips.count
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tips.uid
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tips.id
     *
     * @return the value of user_tips.id
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tips.id
     *
     * @param id the value for user_tips.id
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tips.type
     *
     * @return the value of user_tips.type
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tips.type
     *
     * @param type the value for user_tips.type
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tips.count
     *
     * @return the value of user_tips.count
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tips.count
     *
     * @param count the value for user_tips.count
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tips.uid
     *
     * @return the value of user_tips.uid
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tips.uid
     *
     * @param uid the value for user_tips.uid
     *
     * @mbggenerated Wed Apr 06 15:02:30 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}