package com.me2me.monitor.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class HttpAccess implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_access.id
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_access.http_headers
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    private String httpHeaders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_access.http_uri
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    private String httpUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_access.http_request_method
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    private String httpRequestMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_access.uid
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_access.http_request_params
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    private String httpRequestParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_access.create_time
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_access.status
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_access.id
     *
     * @return the value of http_access.id
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_access.id
     *
     * @param id the value for http_access.id
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_access.http_headers
     *
     * @return the value of http_access.http_headers
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public String getHttpHeaders() {
        return httpHeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_access.http_headers
     *
     * @param httpHeaders the value for http_access.http_headers
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public void setHttpHeaders(String httpHeaders) {
        this.httpHeaders = httpHeaders == null ? null : httpHeaders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_access.http_uri
     *
     * @return the value of http_access.http_uri
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public String getHttpUri() {
        return httpUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_access.http_uri
     *
     * @param httpUri the value for http_access.http_uri
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public void setHttpUri(String httpUri) {
        this.httpUri = httpUri == null ? null : httpUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_access.http_request_method
     *
     * @return the value of http_access.http_request_method
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public String getHttpRequestMethod() {
        return httpRequestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_access.http_request_method
     *
     * @param httpRequestMethod the value for http_access.http_request_method
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public void setHttpRequestMethod(String httpRequestMethod) {
        this.httpRequestMethod = httpRequestMethod == null ? null : httpRequestMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_access.uid
     *
     * @return the value of http_access.uid
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_access.uid
     *
     * @param uid the value for http_access.uid
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_access.http_request_params
     *
     * @return the value of http_access.http_request_params
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public String getHttpRequestParams() {
        return httpRequestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_access.http_request_params
     *
     * @param httpRequestParams the value for http_access.http_request_params
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public void setHttpRequestParams(String httpRequestParams) {
        this.httpRequestParams = httpRequestParams == null ? null : httpRequestParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_access.create_time
     *
     * @return the value of http_access.create_time
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_access.create_time
     *
     * @param createTime the value for http_access.create_time
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_access.status
     *
     * @return the value of http_access.status
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_access.status
     *
     * @param status the value for http_access.status
     *
     * @mbggenerated Fri Apr 21 14:02:01 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}