package com.me2me.content.mapper;

import com.me2me.content.model.BillBoard;
import com.me2me.content.model.BillBoardExample;

import java.util.List;

import com.me2me.content.model.BillBoardRelation;

import org.apache.ibatis.annotations.Param;

public interface BillBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int countByExample(BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int deleteByExample(BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int insert(BillBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int insertSelective(BillBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    List<BillBoard> selectByExample(BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    BillBoard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") BillBoard record, @Param("example") BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int updateByExample(@Param("record") BillBoard record, @Param("example") BillBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int updateByPrimaryKeySelective(BillBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billboard
     *
     * @mbggenerated Wed Mar 22 11:09:13 CST 2017
     */
    int updateByPrimaryKey(BillBoard record);

    /**
     * 找组织|找谁的
     * @param type
     * @return
     */
    List<BillBoardRelation> loadBillBoard(@Param("type") int type);

    /**
     * 获取榜单封面信息
     * @param type
     * @return
     */
    List<Long> loadBillBoardCover(@Param("type") int type);

    /**
     * 分页显示榜单信息
     * @param sourceId
     * @param sinceId
     * @return
     */
    List<BillBoardRelation> loadBillBoardBySinceId(@Param("sourceId") long sourceId, @Param("sinceId") long sinceId, @Param("noTargetIds") List<Long> noTargetIds);
}