package com.me2me.content.mapper;

import com.me2me.content.model.ContentTags;
import com.me2me.content.model.ContentTagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int countByExample(ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int deleteByExample(ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int insert(ContentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int insertSelective(ContentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    List<ContentTags> selectByExample(ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    ContentTags selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") ContentTags record, @Param("example") ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int updateByExample(@Param("record") ContentTags record, @Param("example") ContentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int updateByPrimaryKeySelective(ContentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_tags
     *
     * @mbggenerated Fri Mar 25 13:38:25 CST 2016
     */
    int updateByPrimaryKey(ContentTags record);
}