package com.me2me.content.mapper;

import com.me2me.content.model.EmotionPack;
import com.me2me.content.model.EmotionPackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmotionPackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int countByExample(EmotionPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int deleteByExample(EmotionPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int insert(EmotionPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int insertSelective(EmotionPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    List<EmotionPack> selectByExample(EmotionPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    EmotionPack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") EmotionPack record, @Param("example") EmotionPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int updateByExample(@Param("record") EmotionPack record, @Param("example") EmotionPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int updateByPrimaryKeySelective(EmotionPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_pack
     *
     * @mbggenerated Sat Apr 22 15:52:20 CST 2017
     */
    int updateByPrimaryKey(EmotionPack record);
}