package com.me2me.content.mapper;

import com.me2me.content.model.UserTagLike;
import com.me2me.content.model.UserTagLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTagLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int countByExample(UserTagLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int deleteByExample(UserTagLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int insert(UserTagLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int insertSelective(UserTagLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    List<UserTagLike> selectByExample(UserTagLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    UserTagLike selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserTagLike record, @Param("example") UserTagLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int updateByExample(@Param("record") UserTagLike record, @Param("example") UserTagLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int updateByPrimaryKeySelective(UserTagLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag_like
     *
     * @mbggenerated Tue Aug 08 16:48:46 CST 2017
     */
    int updateByPrimaryKey(UserTagLike record);
}