package com.me2me.live.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class DeleteLog implements BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delete_log.id
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delete_log.type
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delete_log.oid
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    private Long oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delete_log.uid
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delete_log.del_time
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    private Date delTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delete_log.id
     *
     * @return the value of delete_log.id
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delete_log.id
     *
     * @param id the value for delete_log.id
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delete_log.type
     *
     * @return the value of delete_log.type
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delete_log.type
     *
     * @param type the value for delete_log.type
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delete_log.oid
     *
     * @return the value of delete_log.oid
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public Long getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delete_log.oid
     *
     * @param oid the value for delete_log.oid
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public void setOid(Long oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delete_log.uid
     *
     * @return the value of delete_log.uid
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delete_log.uid
     *
     * @param uid the value for delete_log.uid
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delete_log.del_time
     *
     * @return the value of delete_log.del_time
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delete_log.del_time
     *
     * @param delTime the value for delete_log.del_time
     *
     * @mbggenerated Mon Sep 26 16:32:06 CST 2016
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }
}