package com.me2me.live.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class LiveDisplayFragment implements BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.id
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.topic_id
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.uid
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.type
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.fragment
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private String fragment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.fragment_image
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private String fragmentImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.at_uid
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private Long atUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.review_count
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private Integer reviewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.has_barrage
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private Integer hasBarrage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_display_fragment.create_time
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.id
     *
     * @return the value of live_display_fragment.id
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.id
     *
     * @param id the value for live_display_fragment.id
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.topic_id
     *
     * @return the value of live_display_fragment.topic_id
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.topic_id
     *
     * @param topicId the value for live_display_fragment.topic_id
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.uid
     *
     * @return the value of live_display_fragment.uid
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.uid
     *
     * @param uid the value for live_display_fragment.uid
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.type
     *
     * @return the value of live_display_fragment.type
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.type
     *
     * @param type the value for live_display_fragment.type
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.fragment
     *
     * @return the value of live_display_fragment.fragment
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public String getFragment() {
        return fragment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.fragment
     *
     * @param fragment the value for live_display_fragment.fragment
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setFragment(String fragment) {
        this.fragment = fragment == null ? null : fragment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.fragment_image
     *
     * @return the value of live_display_fragment.fragment_image
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public String getFragmentImage() {
        return fragmentImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.fragment_image
     *
     * @param fragmentImage the value for live_display_fragment.fragment_image
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setFragmentImage(String fragmentImage) {
        this.fragmentImage = fragmentImage == null ? null : fragmentImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.at_uid
     *
     * @return the value of live_display_fragment.at_uid
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public Long getAtUid() {
        return atUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.at_uid
     *
     * @param atUid the value for live_display_fragment.at_uid
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setAtUid(Long atUid) {
        this.atUid = atUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.review_count
     *
     * @return the value of live_display_fragment.review_count
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public Integer getReviewCount() {
        return reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.review_count
     *
     * @param reviewCount the value for live_display_fragment.review_count
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setReviewCount(Integer reviewCount) {
        this.reviewCount = reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.has_barrage
     *
     * @return the value of live_display_fragment.has_barrage
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public Integer getHasBarrage() {
        return hasBarrage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.has_barrage
     *
     * @param hasBarrage the value for live_display_fragment.has_barrage
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setHasBarrage(Integer hasBarrage) {
        this.hasBarrage = hasBarrage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_display_fragment.create_time
     *
     * @return the value of live_display_fragment.create_time
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_display_fragment.create_time
     *
     * @param createTime the value for live_display_fragment.create_time
     *
     * @mbggenerated Wed Jul 27 17:10:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}