package com.me2me.live.model;

import java.util.Date;

import com.me2me.common.web.BaseEntity;

public class TopicPriceChangeLog implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_change_log.id
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_change_log.topic_id
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_change_log.uid
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_change_log.type
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_change_log.price
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_change_log.create_time
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_change_log.id
     *
     * @return the value of topic_price_change_log.id
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_change_log.id
     *
     * @param id the value for topic_price_change_log.id
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_change_log.topic_id
     *
     * @return the value of topic_price_change_log.topic_id
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_change_log.topic_id
     *
     * @param topicId the value for topic_price_change_log.topic_id
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_change_log.uid
     *
     * @return the value of topic_price_change_log.uid
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_change_log.uid
     *
     * @param uid the value for topic_price_change_log.uid
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_change_log.type
     *
     * @return the value of topic_price_change_log.type
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_change_log.type
     *
     * @param type the value for topic_price_change_log.type
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_change_log.price
     *
     * @return the value of topic_price_change_log.price
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_change_log.price
     *
     * @param price the value for topic_price_change_log.price
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_change_log.create_time
     *
     * @return the value of topic_price_change_log.create_time
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_change_log.create_time
     *
     * @param createTime the value for topic_price_change_log.create_time
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}