package com.me2me.live.model;

import java.util.Date;

import com.me2me.common.web.BaseEntity;

public class TopicGiven implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_given.id
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_given.title
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_given.cover
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_given.create_time
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_given.uid
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_given.sub_type
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    private Integer subType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_given.summary
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_given.tags
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    private String tags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_given.id
     *
     * @return the value of topic_given.id
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_given.id
     *
     * @param id the value for topic_given.id
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_given.title
     *
     * @return the value of topic_given.title
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_given.title
     *
     * @param title the value for topic_given.title
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_given.cover
     *
     * @return the value of topic_given.cover
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_given.cover
     *
     * @param cover the value for topic_given.cover
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_given.create_time
     *
     * @return the value of topic_given.create_time
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_given.create_time
     *
     * @param createTime the value for topic_given.create_time
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_given.uid
     *
     * @return the value of topic_given.uid
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_given.uid
     *
     * @param uid the value for topic_given.uid
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_given.sub_type
     *
     * @return the value of topic_given.sub_type
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public Integer getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_given.sub_type
     *
     * @param subType the value for topic_given.sub_type
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public void setSubType(Integer subType) {
        this.subType = subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_given.summary
     *
     * @return the value of topic_given.summary
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_given.summary
     *
     * @param summary the value for topic_given.summary
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_given.tags
     *
     * @return the value of topic_given.tags
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_given.tags
     *
     * @param tags the value for topic_given.tags
     *
     * @mbggenerated Wed Jul 19 15:47:30 CST 2017
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }
}