package com.me2me.live.model;

import java.io.Serializable;
import java.util.Date;

public class TopicTagDetail implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag_detail.id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag_detail.topic_id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag_detail.uid
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag_detail.tag_id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag_detail.tag
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag_detail.create_time
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag_detail.status
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_tag_detail.auto_tag
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    private Integer autoTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag_detail.id
     *
     * @return the value of topic_tag_detail.id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag_detail.id
     *
     * @param id the value for topic_tag_detail.id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag_detail.topic_id
     *
     * @return the value of topic_tag_detail.topic_id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag_detail.topic_id
     *
     * @param topicId the value for topic_tag_detail.topic_id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag_detail.uid
     *
     * @return the value of topic_tag_detail.uid
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag_detail.uid
     *
     * @param uid the value for topic_tag_detail.uid
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag_detail.tag_id
     *
     * @return the value of topic_tag_detail.tag_id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag_detail.tag_id
     *
     * @param tagId the value for topic_tag_detail.tag_id
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag_detail.tag
     *
     * @return the value of topic_tag_detail.tag
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag_detail.tag
     *
     * @param tag the value for topic_tag_detail.tag
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag_detail.create_time
     *
     * @return the value of topic_tag_detail.create_time
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag_detail.create_time
     *
     * @param createTime the value for topic_tag_detail.create_time
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag_detail.status
     *
     * @return the value of topic_tag_detail.status
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag_detail.status
     *
     * @param status the value for topic_tag_detail.status
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_tag_detail.auto_tag
     *
     * @return the value of topic_tag_detail.auto_tag
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public Integer getAutoTag() {
        return autoTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_tag_detail.auto_tag
     *
     * @param autoTag the value for topic_tag_detail.auto_tag
     *
     * @mbggenerated Wed Jul 05 10:47:36 CST 2017
     */
    public void setAutoTag(Integer autoTag) {
        this.autoTag = autoTag;
    }
}