package com.me2me.live.model;

import java.util.Date;

import com.me2me.common.web.BaseEntity;

public class TopicPriceHis implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_his.id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_his.topic_id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_his.price
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_price_his.create_time
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_his.id
     *
     * @return the value of topic_price_his.id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_his.id
     *
     * @param id the value for topic_price_his.id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_his.topic_id
     *
     * @return the value of topic_price_his.topic_id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_his.topic_id
     *
     * @param topicId the value for topic_price_his.topic_id
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_his.price
     *
     * @return the value of topic_price_his.price
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_his.price
     *
     * @param price the value for topic_price_his.price
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_price_his.create_time
     *
     * @return the value of topic_price_his.create_time
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_price_his.create_time
     *
     * @param createTime the value for topic_price_his.create_time
     *
     * @mbggenerated Wed Jun 14 16:30:19 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}