package com.me2me.live.mapper;

import com.me2me.live.model.LiveFavorite;
import com.me2me.live.model.LiveFavoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int countByExample(LiveFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int deleteByExample(LiveFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int insert(LiveFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int insertSelective(LiveFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    List<LiveFavorite> selectByExample(LiveFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    LiveFavorite selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") LiveFavorite record, @Param("example") LiveFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int updateByExample(@Param("record") LiveFavorite record, @Param("example") LiveFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int updateByPrimaryKeySelective(LiveFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_favorite
     *
     * @mbggenerated Wed Apr 13 17:04:40 CST 2016
     */
    int updateByPrimaryKey(LiveFavorite record);
}