package com.me2me.live.mapper;

import com.me2me.live.model.LotteryInfo;
import com.me2me.live.model.LotteryInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LotteryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int countByExample(LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int deleteByExample(LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int insert(LotteryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int insertSelective(LotteryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    List<LotteryInfo> selectByExample(LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    LotteryInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") LotteryInfo record, @Param("example") LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int updateByExample(@Param("record") LotteryInfo record, @Param("example") LotteryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int updateByPrimaryKeySelective(LotteryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Mon Aug 07 10:57:33 CST 2017
     */
    int updateByPrimaryKey(LotteryInfo record);
}