package com.me2me.live.mapper;

import com.me2me.live.model.QuotationInfo;
import com.me2me.live.model.QuotationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuotationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int countByExample(QuotationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int deleteByExample(QuotationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int insert(QuotationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int insertSelective(QuotationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    List<QuotationInfo> selectByExample(QuotationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    QuotationInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") QuotationInfo record, @Param("example") QuotationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int updateByExample(@Param("record") QuotationInfo record, @Param("example") QuotationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int updateByPrimaryKeySelective(QuotationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation_info
     *
     * @mbggenerated Thu Jul 20 13:53:53 CST 2017
     */
    int updateByPrimaryKey(QuotationInfo record);


    /**
     *随机获取一条语录
     * @return
     */
    QuotationInfo getQuotationInfo(@Param("type") int type);

    List<QuotationInfo> selectListQuotationInfo(@Param("limit") int limit);
}