package com.me2me.live.mapper;

import com.me2me.live.model.SignSaveRecord;
import com.me2me.live.model.SignSaveRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SignSaveRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int countByExample(SignSaveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int deleteByExample(SignSaveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int insert(SignSaveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int insertSelective(SignSaveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    List<SignSaveRecord> selectByExample(SignSaveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    SignSaveRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") SignSaveRecord record, @Param("example") SignSaveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int updateByExample(@Param("record") SignSaveRecord record, @Param("example") SignSaveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int updateByPrimaryKeySelective(SignSaveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_save_record
     *
     * @mbggenerated Thu Jul 20 17:17:11 CST 2017
     */
    int updateByPrimaryKey(SignSaveRecord record);
}