package com.me2me.live.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.me2me.live.dto.SearchTopicDto;
import com.me2me.live.model.Topic;
import com.me2me.live.model.Topic2;
import com.me2me.live.model.TopicExample;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    int countByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    int deleteByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    int insertSelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    List<Topic> selectByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    Topic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    int updateByExample(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:26 CST 2017
     */
    int updateByPrimaryKeySelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Thu Nov 23 15:39:27 CST 2017
     */
    int updateByPrimaryKey(Topic record);
    
 void truncateKingdomCountDay();
    
    void statKingdomCountDay();
    
    Topic getRandomDropaRoundAlgorithm(Map<String ,Object> map);

    List<Topic2> getMyLivesByUpdateTimeNew(Map map);
    /**
     * 获取一个王国分页。包含统计字段， 巨慢，仅供后台使用。
     * @author zhangjiwei
     * @date Mar 21, 2017
     * @param map
     * @return
     */
    @Deprecated
    List<SearchTopicDto> getTopicPage(Map map);
    /**
     * 王国分页统计 巨慢，包含统计字段，仅供后台使用。
     * @author zhangjiwei
     * @date Mar 21, 2017
     * @param map
     * @return
     */
    @Deprecated
    long countTopicForPage(Map map);
    /**
     * 随机查询一个某标签下的王国
     * @author zhangjiwei
     * @date Jul 3, 2017
     * @param map
     * @return
     */
    Topic getRandomTopicByTag(Map<String ,Object> map);
    
}