package com.me2me.live.mapper;

import com.me2me.live.dto.SearchDropAroundTopicDto;
import com.me2me.live.dto.ShowTopicListDto.ShowTopicElement;
import com.me2me.live.model.TopicDroparound;
import com.me2me.live.model.TopicDroparoundExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TopicDroparoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int countByExample(TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int deleteByExample(TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int insert(TopicDroparound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int insertSelective(TopicDroparound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    List<TopicDroparound> selectByExample(TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    TopicDroparound selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") TopicDroparound record, @Param("example") TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int updateByExample(@Param("record") TopicDroparound record, @Param("example") TopicDroparoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int updateByPrimaryKeySelective(TopicDroparound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_droparound
     *
     * @mbggenerated Fri Mar 17 10:03:44 CST 2017
     */
    int updateByPrimaryKey(TopicDroparound record);

    TopicDroparound getRandomDropaRound(Map<String ,Object> map);
    /**
     * 获取串门王国分页。
     * @author zhangjiwei
     * @date Mar 20, 2017
     * @return
     */
    List<SearchDropAroundTopicDto> getDropAroundKingdomPage(Map<String,Object> data);
    /**
     * count from droparound kingdom
     * @author zhangjiwei
     * @date Mar 20, 2017
     * @param obj
     * @return
     */
	int countDropAroundKingdomPage(Map<String, Object> obj);

}