package com.me2me.live.mapper;

import com.me2me.live.model.TopicPriceChangeLog;
import com.me2me.live.model.TopicPriceChangeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicPriceChangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int countByExample(TopicPriceChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int deleteByExample(TopicPriceChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int insert(TopicPriceChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int insertSelective(TopicPriceChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    List<TopicPriceChangeLog> selectByExample(TopicPriceChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    TopicPriceChangeLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") TopicPriceChangeLog record, @Param("example") TopicPriceChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int updateByExample(@Param("record") TopicPriceChangeLog record, @Param("example") TopicPriceChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int updateByPrimaryKeySelective(TopicPriceChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_price_change_log
     *
     * @mbggenerated Tue Aug 15 15:25:27 CST 2017
     */
    int updateByPrimaryKey(TopicPriceChangeLog record);
}