package com.me2me.live.mapper;

import com.me2me.live.model.TopicAggregation;
import com.me2me.live.model.TopicAggregationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicAggregationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int countByExample(TopicAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int deleteByExample(TopicAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int insert(TopicAggregation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int insertSelective(TopicAggregation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    List<TopicAggregation> selectByExample(TopicAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    TopicAggregation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") TopicAggregation record, @Param("example") TopicAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int updateByExample(@Param("record") TopicAggregation record, @Param("example") TopicAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int updateByPrimaryKeySelective(TopicAggregation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_aggregation
     *
     * @mbggenerated Sun Jan 22 15:31:22 CST 2017
     */
    int updateByPrimaryKey(TopicAggregation record);
}