package com.me2me.live.mapper;

import com.me2me.live.model.UserStealLog;
import com.me2me.live.model.UserStealLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserStealLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int countByExample(UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int deleteByExample(UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int insert(UserStealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int insertSelective(UserStealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    List<UserStealLog> selectByExample(UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    UserStealLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserStealLog record, @Param("example") UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int updateByExample(@Param("record") UserStealLog record, @Param("example") UserStealLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int updateByPrimaryKeySelective(UserStealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_steal_log
     *
     * @mbggenerated Tue Jul 18 11:29:25 CST 2017
     */
    int updateByPrimaryKey(UserStealLog record);
}