package com.me2me.live.mapper;

import com.me2me.live.model.VoteOption;
import com.me2me.live.model.VoteOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int countByExample(VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int deleteByExample(VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int insert(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int insertSelective(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    List<VoteOption> selectByExample(VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    VoteOption selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") VoteOption record, @Param("example") VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int updateByExample(@Param("record") VoteOption record, @Param("example") VoteOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int updateByPrimaryKeySelective(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int updateByPrimaryKey(VoteOption record);
}