package com.me2me.live.mapper;

import com.me2me.live.model.VoteRecord;
import com.me2me.live.model.VoteRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int countByExample(VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int deleteByExample(VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int insert(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int insertSelective(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    List<VoteRecord> selectByExample(VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    VoteRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") VoteRecord record, @Param("example") VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int updateByExample(@Param("record") VoteRecord record, @Param("example") VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int updateByPrimaryKeySelective(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbggenerated Tue May 09 16:04:57 CST 2017
     */
    int updateByPrimaryKey(VoteRecord record);
}