package com.me2me.activity.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class AdoubleTopicApply implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_double_topic_apply.id
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_double_topic_apply.uid
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_double_topic_apply.target_uid
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    private Long targetUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_double_topic_apply.type
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_double_topic_apply.status
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_double_topic_apply.create_time
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_double_topic_apply.number
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_double_topic_apply.id
     *
     * @return the value of a_double_topic_apply.id
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_double_topic_apply.id
     *
     * @param id the value for a_double_topic_apply.id
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_double_topic_apply.uid
     *
     * @return the value of a_double_topic_apply.uid
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_double_topic_apply.uid
     *
     * @param uid the value for a_double_topic_apply.uid
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_double_topic_apply.target_uid
     *
     * @return the value of a_double_topic_apply.target_uid
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public Long getTargetUid() {
        return targetUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_double_topic_apply.target_uid
     *
     * @param targetUid the value for a_double_topic_apply.target_uid
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public void setTargetUid(Long targetUid) {
        this.targetUid = targetUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_double_topic_apply.type
     *
     * @return the value of a_double_topic_apply.type
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_double_topic_apply.type
     *
     * @param type the value for a_double_topic_apply.type
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_double_topic_apply.status
     *
     * @return the value of a_double_topic_apply.status
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_double_topic_apply.status
     *
     * @param status the value for a_double_topic_apply.status
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_double_topic_apply.create_time
     *
     * @return the value of a_double_topic_apply.create_time
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_double_topic_apply.create_time
     *
     * @param createTime the value for a_double_topic_apply.create_time
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_double_topic_apply.number
     *
     * @return the value of a_double_topic_apply.number
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_double_topic_apply.number
     *
     * @param number the value for a_double_topic_apply.number
     *
     * @mbggenerated Thu Dec 08 20:49:19 CST 2016
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}