package com.me2me.activity.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class AforcedPairing implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.id
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.auid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Long auid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.uid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.status
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.sex
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.target_uid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Long targetUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.target_auid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Long targetAuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.create_time
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_forced_pairing.update_time
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.id
     *
     * @return the value of a_forced_pairing.id
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.id
     *
     * @param id the value for a_forced_pairing.id
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.auid
     *
     * @return the value of a_forced_pairing.auid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Long getAuid() {
        return auid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.auid
     *
     * @param auid the value for a_forced_pairing.auid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setAuid(Long auid) {
        this.auid = auid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.uid
     *
     * @return the value of a_forced_pairing.uid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.uid
     *
     * @param uid the value for a_forced_pairing.uid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.status
     *
     * @return the value of a_forced_pairing.status
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.status
     *
     * @param status the value for a_forced_pairing.status
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.sex
     *
     * @return the value of a_forced_pairing.sex
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.sex
     *
     * @param sex the value for a_forced_pairing.sex
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.target_uid
     *
     * @return the value of a_forced_pairing.target_uid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Long getTargetUid() {
        return targetUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.target_uid
     *
     * @param targetUid the value for a_forced_pairing.target_uid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setTargetUid(Long targetUid) {
        this.targetUid = targetUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.target_auid
     *
     * @return the value of a_forced_pairing.target_auid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Long getTargetAuid() {
        return targetAuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.target_auid
     *
     * @param targetAuid the value for a_forced_pairing.target_auid
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setTargetAuid(Long targetAuid) {
        this.targetAuid = targetAuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.create_time
     *
     * @return the value of a_forced_pairing.create_time
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.create_time
     *
     * @param createTime the value for a_forced_pairing.create_time
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_forced_pairing.update_time
     *
     * @return the value of a_forced_pairing.update_time
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_forced_pairing.update_time
     *
     * @param updateTime the value for a_forced_pairing.update_time
     *
     * @mbggenerated Thu Dec 15 19:35:29 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}