package com.me2me.activity.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class AkingDom implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_kingdom.id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_kingdom.uid
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_kingdom.topic_id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_kingdom.create_time
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_kingdom.status
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_kingdom.activity_id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_kingdom.hot
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    private Long hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_kingdom.conditions
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    private Integer conditions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_kingdom.id
     *
     * @return the value of a_kingdom.id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_kingdom.id
     *
     * @param id the value for a_kingdom.id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_kingdom.uid
     *
     * @return the value of a_kingdom.uid
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_kingdom.uid
     *
     * @param uid the value for a_kingdom.uid
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_kingdom.topic_id
     *
     * @return the value of a_kingdom.topic_id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_kingdom.topic_id
     *
     * @param topicId the value for a_kingdom.topic_id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_kingdom.create_time
     *
     * @return the value of a_kingdom.create_time
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_kingdom.create_time
     *
     * @param createTime the value for a_kingdom.create_time
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_kingdom.status
     *
     * @return the value of a_kingdom.status
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_kingdom.status
     *
     * @param status the value for a_kingdom.status
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_kingdom.activity_id
     *
     * @return the value of a_kingdom.activity_id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_kingdom.activity_id
     *
     * @param activityId the value for a_kingdom.activity_id
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_kingdom.hot
     *
     * @return the value of a_kingdom.hot
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public Long getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_kingdom.hot
     *
     * @param hot the value for a_kingdom.hot
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public void setHot(Long hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_kingdom.conditions
     *
     * @return the value of a_kingdom.conditions
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public Integer getConditions() {
        return conditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_kingdom.conditions
     *
     * @param conditions the value for a_kingdom.conditions
     *
     * @mbggenerated Fri Jan 06 16:58:28 CST 2017
     */
    public void setConditions(Integer conditions) {
        this.conditions = conditions;
    }
}