package com.me2me.activity.model;

public class AtaskWithBLOBs extends Atask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_task.content
     *
     * @mbggenerated Wed Dec 28 21:04:28 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_task.mili_content
     *
     * @mbggenerated Wed Dec 28 21:04:28 CST 2016
     */
    private String miliContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_task.content
     *
     * @return the value of a_task.content
     *
     * @mbggenerated Wed Dec 28 21:04:28 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_task.content
     *
     * @param content the value for a_task.content
     *
     * @mbggenerated Wed Dec 28 21:04:28 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_task.mili_content
     *
     * @return the value of a_task.mili_content
     *
     * @mbggenerated Wed Dec 28 21:04:28 CST 2016
     */
    public String getMiliContent() {
        return miliContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_task.mili_content
     *
     * @param miliContent the value for a_task.mili_content
     *
     * @mbggenerated Wed Dec 28 21:04:28 CST 2016
     */
    public void setMiliContent(String miliContent) {
        this.miliContent = miliContent == null ? null : miliContent.trim();
    }
}