package com.me2me.activity.model;

import java.util.Date;

import com.me2me.common.web.BaseEntity;

public class GameUserInfo implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_user_info.id
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_user_info.uid
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_user_info.coins
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    private Integer coins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_user_info.create_time
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_user_info.game_channel
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    private Integer gameChannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_user_info.id
     *
     * @return the value of game_user_info.id
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_user_info.id
     *
     * @param id the value for game_user_info.id
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_user_info.uid
     *
     * @return the value of game_user_info.uid
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_user_info.uid
     *
     * @param uid the value for game_user_info.uid
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_user_info.coins
     *
     * @return the value of game_user_info.coins
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public Integer getCoins() {
        return coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_user_info.coins
     *
     * @param coins the value for game_user_info.coins
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public void setCoins(Integer coins) {
        this.coins = coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_user_info.create_time
     *
     * @return the value of game_user_info.create_time
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_user_info.create_time
     *
     * @param createTime the value for game_user_info.create_time
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_user_info.game_channel
     *
     * @return the value of game_user_info.game_channel
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public Integer getGameChannel() {
        return gameChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_user_info.game_channel
     *
     * @param gameChannel the value for game_user_info.game_channel
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    public void setGameChannel(Integer gameChannel) {
        this.gameChannel = gameChannel;
    }
}