package com.me2me.activity.model;

import com.me2me.common.web.BaseEntity;

import java.util.Date;

public class LuckStatus implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.id
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.version
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.activity_name
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private Integer activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.channel
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.award_term
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private String awardTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.award_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private Integer awardStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.operate_mobile
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private String operateMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.award_sum_chance
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private Integer awardSumChance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.start_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.end_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_status.create_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.id
     *
     * @return the value of luck_status.id
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.id
     *
     * @param id the value for luck_status.id
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.version
     *
     * @return the value of luck_status.version
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.version
     *
     * @param version the value for luck_status.version
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.activity_name
     *
     * @return the value of luck_status.activity_name
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public Integer getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.activity_name
     *
     * @param activityName the value for luck_status.activity_name
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setActivityName(Integer activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.channel
     *
     * @return the value of luck_status.channel
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.channel
     *
     * @param channel the value for luck_status.channel
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.award_term
     *
     * @return the value of luck_status.award_term
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public String getAwardTerm() {
        return awardTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.award_term
     *
     * @param awardTerm the value for luck_status.award_term
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setAwardTerm(String awardTerm) {
        this.awardTerm = awardTerm == null ? null : awardTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.award_status
     *
     * @return the value of luck_status.award_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public Integer getAwardStatus() {
        return awardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.award_status
     *
     * @param awardStatus the value for luck_status.award_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setAwardStatus(Integer awardStatus) {
        this.awardStatus = awardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.operate_mobile
     *
     * @return the value of luck_status.operate_mobile
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public String getOperateMobile() {
        return operateMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.operate_mobile
     *
     * @param operateMobile the value for luck_status.operate_mobile
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setOperateMobile(String operateMobile) {
        this.operateMobile = operateMobile == null ? null : operateMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.award_sum_chance
     *
     * @return the value of luck_status.award_sum_chance
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public Integer getAwardSumChance() {
        return awardSumChance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.award_sum_chance
     *
     * @param awardSumChance the value for luck_status.award_sum_chance
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setAwardSumChance(Integer awardSumChance) {
        this.awardSumChance = awardSumChance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.start_time
     *
     * @return the value of luck_status.start_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.start_time
     *
     * @param startTime the value for luck_status.start_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.end_time
     *
     * @return the value of luck_status.end_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.end_time
     *
     * @param endTime the value for luck_status.end_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luck_status.create_time
     *
     * @return the value of luck_status.create_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luck_status.create_time
     *
     * @param createTime the value for luck_status.create_time
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}