package com.me2me.activity.mapper;

import com.me2me.activity.model.AcommonHotDetail;
import com.me2me.activity.model.AcommonHotDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcommonHotDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int countByExample(AcommonHotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int deleteByExample(AcommonHotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int insert(AcommonHotDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int insertSelective(AcommonHotDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    List<AcommonHotDetail> selectByExample(AcommonHotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    AcommonHotDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcommonHotDetail record, @Param("example") AcommonHotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int updateByExample(@Param("record") AcommonHotDetail record, @Param("example") AcommonHotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int updateByPrimaryKeySelective(AcommonHotDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_common_hot_detail
     *
     * @mbggenerated Thu Apr 20 22:00:06 CST 2017
     */
    int updateByPrimaryKey(AcommonHotDetail record);
}