package com.me2me.activity.mapper;

import com.me2me.activity.model.ArecommendUser;
import com.me2me.activity.model.ArecommendUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArecommendUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int countByExample(ArecommendUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int deleteByExample(ArecommendUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int insert(ArecommendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int insertSelective(ArecommendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    List<ArecommendUser> selectByExample(ArecommendUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    ArecommendUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") ArecommendUser record, @Param("example") ArecommendUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int updateByExample(@Param("record") ArecommendUser record, @Param("example") ArecommendUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int updateByPrimaryKeySelective(ArecommendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_recommend_user
     *
     * @mbggenerated Wed Dec 14 15:38:13 CST 2016
     */
    int updateByPrimaryKey(ArecommendUser record);
}