package com.me2me.activity.mapper;

import com.me2me.activity.model.GameUserInfo;
import com.me2me.activity.model.GameUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int countByExample(GameUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int deleteByExample(GameUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int insert(GameUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int insertSelective(GameUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    List<GameUserInfo> selectByExample(GameUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    GameUserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") GameUserInfo record, @Param("example") GameUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int updateByExample(@Param("record") GameUserInfo record, @Param("example") GameUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int updateByPrimaryKeySelective(GameUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_user_info
     *
     * @mbggenerated Mon Oct 16 12:21:05 CST 2017
     */
    int updateByPrimaryKey(GameUserInfo record);
    
    void userInfoAddCoinsByGameId(GameUserInfo gameUserInfo);

	void gameUserInfoSubCoinsByUidAndCoins(GameUserInfo gameUserInfo);

	void userProfileAddAvailableCoinByCoinsAndUid(@Param("coins")int coins, @Param("uid")long uid);

}