package com.me2me.activity.mapper;

import com.me2me.activity.dto.LuckActStat2DTO;
import com.me2me.activity.dto.LuckActStatDTO;
import com.me2me.activity.model.LuckAct;
import com.me2me.activity.model.LuckActExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface LuckActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int countByExample(LuckActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int deleteByExample(LuckActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int insert(LuckAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int insertSelective(LuckAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    List<LuckAct> selectByExample(LuckActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    LuckAct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") LuckAct record, @Param("example") LuckActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int updateByExample(@Param("record") LuckAct record, @Param("example") LuckActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int updateByPrimaryKeySelective(LuckAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_act
     *
     * @mbggenerated Wed Oct 19 16:27:34 CST 2016
     */
    int updateByPrimaryKey(LuckAct record);
    
    List<LuckActStat2DTO> getLuctActStat2ByActivityName(int activityName);
    
    List<LuckActStatDTO> getLuctActStatByActivityName(@Param("activityName")int activityName, @Param("startTime")Date startTime, @Param("endTime")Date endTime);
}