package com.me2me.activity.mapper;

import com.me2me.activity.model.LuckStatus;
import com.me2me.activity.model.LuckStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LuckStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int countByExample(LuckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int deleteByExample(LuckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int insert(LuckStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int insertSelective(LuckStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    List<LuckStatus> selectByExample(LuckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    LuckStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") LuckStatus record, @Param("example") LuckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int updateByExample(@Param("record") LuckStatus record, @Param("example") LuckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int updateByPrimaryKeySelective(LuckStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_status
     *
     * @mbggenerated Thu Nov 03 12:58:07 CST 2016
     */
    int updateByPrimaryKey(LuckStatus record);
}