package com.me2me.activity.mapper;

import com.me2me.activity.model.LuckPrize;
import com.me2me.activity.model.LuckPrizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LuckPrizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int countByExample(LuckPrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int deleteByExample(LuckPrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int insert(LuckPrize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int insertSelective(LuckPrize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    List<LuckPrize> selectByExample(LuckPrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    LuckPrize selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") LuckPrize record, @Param("example") LuckPrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int updateByExample(@Param("record") LuckPrize record, @Param("example") LuckPrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int updateByPrimaryKeySelective(LuckPrize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_prize
     *
     * @mbggenerated Wed Oct 19 18:10:23 CST 2016
     */
    int updateByPrimaryKey(LuckPrize record);
}