package com.me2me.monitor.mapper;

import com.me2me.monitor.model.AccessTrack;
import com.me2me.monitor.model.AccessTrackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int countByExample(AccessTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int deleteByExample(AccessTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int insert(AccessTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int insertSelective(AccessTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    List<AccessTrack> selectByExample(AccessTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    AccessTrack selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") AccessTrack record, @Param("example") AccessTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int updateByExample(@Param("record") AccessTrack record, @Param("example") AccessTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int updateByPrimaryKeySelective(AccessTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_track
     *
     * @mbggenerated Mon Jun 13 20:16:07 CST 2016
     */
    int updateByPrimaryKey(AccessTrack record);
}