package com.me2me.user.mapper;

import com.me2me.user.model.EmotionRecord;
import com.me2me.user.model.EmotionRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmotionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int countByExample(EmotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int deleteByExample(EmotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int insert(EmotionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int insertSelective(EmotionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    List<EmotionRecord> selectByExample(EmotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    EmotionRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") EmotionRecord record, @Param("example") EmotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int updateByExample(@Param("record") EmotionRecord record, @Param("example") EmotionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int updateByPrimaryKeySelective(EmotionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_record
     *
     * @mbggenerated Tue May 23 14:16:14 CST 2017
     */
    int updateByPrimaryKey(EmotionRecord record);
}