package com.me2me.user.mapper;

import com.me2me.user.model.UserNoticeUnread;
import com.me2me.user.model.UserNoticeUnreadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserNoticeUnreadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int countByExample(UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int deleteByExample(UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int insert(UserNoticeUnread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int insertSelective(UserNoticeUnread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    List<UserNoticeUnread> selectByExample(UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    UserNoticeUnread selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserNoticeUnread record, @Param("example") UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int updateByExample(@Param("record") UserNoticeUnread record, @Param("example") UserNoticeUnreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int updateByPrimaryKeySelective(UserNoticeUnread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notice_unread
     *
     * @mbggenerated Tue May 09 17:21:14 CST 2017
     */
    int updateByPrimaryKey(UserNoticeUnread record);
}