package com.me2me.user.mapper;

import com.me2me.user.model.UserTagsRecord;
import com.me2me.user.model.UserTagsRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTagsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int countByExample(UserTagsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int deleteByExample(UserTagsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int insert(UserTagsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int insertSelective(UserTagsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    List<UserTagsRecord> selectByExample(UserTagsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    UserTagsRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserTagsRecord record, @Param("example") UserTagsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int updateByExample(@Param("record") UserTagsRecord record, @Param("example") UserTagsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int updateByPrimaryKeySelective(UserTagsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tags_record
     *
     * @mbggenerated Tue Apr 12 19:33:04 CST 2016
     */
    int updateByPrimaryKey(UserTagsRecord record);
}