package com.me2me.user.mapper;

import com.me2me.user.model.UserFirstLog;
import com.me2me.user.model.UserFirstLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFirstLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int countByExample(UserFirstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int deleteByExample(UserFirstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int insert(UserFirstLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int insertSelective(UserFirstLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    List<UserFirstLog> selectByExample(UserFirstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    UserFirstLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserFirstLog record, @Param("example") UserFirstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int updateByExample(@Param("record") UserFirstLog record, @Param("example") UserFirstLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int updateByPrimaryKeySelective(UserFirstLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_first_log
     *
     * @mbggenerated Tue Jul 25 10:59:49 CST 2017
     */
    int updateByPrimaryKey(UserFirstLog record);
}