package com.me2me.user.mapper;

import com.me2me.user.model.UserBlackList;
import com.me2me.user.model.UserBlackListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBlackListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int countByExample(UserBlackListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int deleteByExample(UserBlackListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int insert(UserBlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int insertSelective(UserBlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    List<UserBlackList> selectByExample(UserBlackListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    UserBlackList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserBlackList record, @Param("example") UserBlackListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int updateByExample(@Param("record") UserBlackList record, @Param("example") UserBlackListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int updateByPrimaryKeySelective(UserBlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black_list
     *
     * @mbggenerated Sun Jul 16 14:09:17 CST 2017
     */
    int updateByPrimaryKey(UserBlackList record);
}